### ISSUE TITLE
define_surv_fit is not available in the latest version

### ISSUE THREAD

**Issue by Eva018** [aphp/heemod#10]
Hi, I just felt define_surv_fit is not available anymore after I updated the package. Maybe it is because it isn't contained in the latest version 0.16.0. Instead, it comes from version 0.16.0.9001, but I have no idea how to download this version back. Thanks for your clarification a lot.

**Comment by KZARCA** [comment]
Hi, did you try: `devtools::install_github("aphp/heemod")`?

**Comment by Eva018** [comment]
Hi, I just tried this code but it still says "could not find function "define_surv_fit"". I can use it last week but it pops up error message constantly today when I reload my codes.
