### ISSUE TITLE
Error plot dsa

### ISSUE THREAD

**Issue by 3stebanorozco** [aphp/heemod#4]
Hello,

Mi name is Esteban and I have a problem versions 0.15.1 and  0.15.0.

When I try to construct the graphic of dsa with the follow:

 plot(res_dsa,
     strategy = "mono",
     result = "cost",
     type = "simple")

The code built the graphic in bad way, Don't show the lines and represent a parameter that I didn't define. Even, in the vignette I can see the mistake: https://cran.r-project.org/web/packages/heemod/vignettes/f_sensitivity.html

I hope you can help me.

Regards.

**Comment by KZARCA** [comment]
Hi Esteban, thanks for your bug report. I'm checking what's wrong

**Comment by KZARCA** [comment]
Hi Esteban, thanks for your bug report. I'm checking what's wrong

**Comment by KZARCA** [comment]
Your issue is now fixed. 
Please install the new version from github : install.github("aphp/heemod")
