### ISSUE TITLE
dsa in heemod package

### ISSUE THREAD

**Issue by huipharmacist** [aphp/heemod#6]
When doing dsa, some parameters in the dsa diagram are not displayed. Why？thank you.
#5 
![image](https://github.com/aphp/heemod/assets/134043085/ae69000e-06ce-4b48-aff0-0b377098a655)

**Comment by huipharmacist** [comment]
define_dsa<- define_dsa(cLapa,26, 27.6,cCape, 1.2, 1.8,BSA, 1.5, 1.9, uS, 0.63, 0.77,uR, 0.7, 0.924,uP, 0.45, 0.55)
result_dsa<- run_dsa(res_mod, dsa = define_dsa)
plot(result_dsa, result = "icer", type = "difference")

The code should be fine. I want to ask that base ICER is not included between the minimum and maximum range of the cLapa parameter in the figure above, but it still extends to base ICER. So numbers are covered up. In cases like this, how to modify the code so that it shows the real results. I hope you can help me.

**Comment by huipharmacist** [comment]
Is there any way to solve it, thank you.

**Comment by KZARCA** [comment]
The problem I found is that the ICER for the 2 extreme values of your parameter does not contain the baseline ICER.
I've never seen this before. It is possible that your code contains an error.

**Comment by huipharmacist** [comment]
thank you, is there any way to adjust the graph manually through ggplot

**Comment by KZARCA** [comment]
Hi,
the function is [plot.dsa](https://github.com/aphp/heemod/blob/master/R/sensitivity_print.R#L31); what you could do is creating another function based on the code of plot.dsa

Best

**Comment by huipharmacist** [comment]
Is it convenient to send an example
