### ISSUE TITLE
Running model with tabular inputs, but confused about how to define state_time_limit and plotting state memberships?

### ISSUE THREAD

**Issue by sw3554** [aphp/heemod#9]
Hi, thank you for making this package, and I really appreciate it!

As the title says, I'm confused about state_time_limit and state membership plotting when using tabular inputs.
My code is:
mod<-run_model_tabular(
  location="...",
  reference = "ref.csv",
  run_dsa = F,
  run_psa = F,
  run_demo = F
)
plot(mod,type="counts")

I tried to define state_time_limit in the options file and in run_model_tabular (with value 3) and got errors (unknown option and unknow argument).
I then defined it in the parameters file, but that didn't seem to work, because in the results I get states like statename_1, statename_2, all the way to the number of cycles.

Edit: I figured out getting the plot and state counts. I'm now wondering, is there a convenient way to get the inflow to each state by cycle? I see there's a model$model_runs$eval_strategy_list$strategy$e_inflow, but it seems to be all 0s.

**Comment by KZARCA** [comment]
Hi,
Sorry for the delay of my reply, I was away for a couple of weeks.
Would you mind sending an example of file for which you have these questions?
Best
